/** AUTO-GENERATED by scripts/generate-config.mjs (local) — edit js/config.shared.js */
/** ブラウザはこのファイルのみ読み込みます（config.shared.js は Node 用ソース）。 */

export const DATA_MODE = "local";

export const SITE_CONFIG = Object.freeze({
  "newsJsonUrl": "./data/news.json",
  "moviesCsvUrl": "./data/movies.csv",
  "eventsCsvUrl": "./data/events.csv",
  "speakersCsvUrl": "./data/speakers.csv",
  "exhibitionsCsvUrl": "./data/exhibitions.csv",
  "eventSpeakerIds": {
    "evt-01": [
      "spk-001",
      "spk-002",
      "spk-003",
      "spk-004"
    ],
    "evt-02": [
      "spk-005",
      "spk-006"
    ],
    "evt-03": [
      "spk-007",
      "spk-008",
      "spk-009",
      "spk-010"
    ],
    "evt-04": [
      "spk-011",
      "spk-012",
      "spk-013"
    ],
    "evt-05": [
      "spk-007",
      "spk-006"
    ]
  },
  "eventFeaturedSpeakerIds": {
    "evt-01": [
      "spk-001"
    ],
    "evt-02": [
      "spk-005"
    ],
    "evt-03": [
      "spk-008",
      "spk-009",
      "spk-010"
    ],
    "evt-04": [
      "spk-011"
    ],
    "evt-05": []
  },
  "eventWideSubSpeakerIds": {
    "evt-01": [
      "spk-004"
    ]
  },
  "googleMapsApiKey": "AIzaSyDSfeNa_ftv6Orh--hQQOvZOVyRCuUvBqg"
});

export const SHEET_DATA_URLS = Object.freeze({
  "moviesCsvUrl": "https://docs.google.com/spreadsheets/d/1hXldiXUl2klbJe6v7BraKEFCXL8cxd5WAjc0RRNzlPo/export?format=csv&gid=1499163471",
  "eventsCsvUrl": "https://docs.google.com/spreadsheets/d/1hXldiXUl2klbJe6v7BraKEFCXL8cxd5WAjc0RRNzlPo/export?format=csv&gid=651546877",
  "speakersCsvUrl": "https://docs.google.com/spreadsheets/d/1hXldiXUl2klbJe6v7BraKEFCXL8cxd5WAjc0RRNzlPo/export?format=csv&gid=1429540203",
  "exhibitionsCsvUrl": "https://docs.google.com/spreadsheets/d/1hXldiXUl2klbJe6v7BraKEFCXL8cxd5WAjc0RRNzlPo/export?format=csv&gid=1913009152"
});
export const LOCAL_DATA_URLS = Object.freeze({
  "moviesCsvUrl": "./data/movies.csv",
  "eventsCsvUrl": "./data/events.csv",
  "speakersCsvUrl": "./data/speakers.csv",
  "exhibitionsCsvUrl": "./data/exhibitions.csv"
});
export const DATA_URLS = Object.freeze({
  "sheet": {
    "moviesCsvUrl": "https://docs.google.com/spreadsheets/d/1hXldiXUl2klbJe6v7BraKEFCXL8cxd5WAjc0RRNzlPo/export?format=csv&gid=1499163471",
    "eventsCsvUrl": "https://docs.google.com/spreadsheets/d/1hXldiXUl2klbJe6v7BraKEFCXL8cxd5WAjc0RRNzlPo/export?format=csv&gid=651546877",
    "speakersCsvUrl": "https://docs.google.com/spreadsheets/d/1hXldiXUl2klbJe6v7BraKEFCXL8cxd5WAjc0RRNzlPo/export?format=csv&gid=1429540203",
    "exhibitionsCsvUrl": "https://docs.google.com/spreadsheets/d/1hXldiXUl2klbJe6v7BraKEFCXL8cxd5WAjc0RRNzlPo/export?format=csv&gid=1913009152"
  },
  "local": {
    "moviesCsvUrl": "./data/movies.csv",
    "eventsCsvUrl": "./data/events.csv",
    "speakersCsvUrl": "./data/speakers.csv",
    "exhibitionsCsvUrl": "./data/exhibitions.csv"
  }
});

export const PROGRAM_TIMELINE = Object.freeze({
  "axisStartMin": 540,
  "axisEndMin": 1200,
  "screening": {
    "label": "卒業制作選抜展\n「南女シネマ」",
    "timeDisplay": "17:00～19:10",
    "start": "17:00",
    "end": "19:10",
    "venue": "元町映画館"
  },
  "exhibition": {
    "label": "作品展示",
    "start": "10:00",
    "end": "18:00",
    "venue": "こうべまちづくり会館 2F ホール、3F多目的室"
  }
});

export const EVENT_CATEGORY_LABELS = Object.freeze({
  "lecture": "レクチャー",
  "workshop": "ワークショップ",
  "permanent": "常設"
});

export const DIALOG_PROGRAM_LABELS = Object.freeze({
  "screening": "卒業制作選抜展「南女シネマ」",
  "lecture": "レクチャー",
  "workshop": "ワークショップ",
  "permanent": "常設企画"
});

export function dialogProgramLabelMod(cat) {
  if (cat === "workshop") return "workshop";
  if (cat === "permanent") return "permanent";
  if (cat === "screening") return "screening";
  return "lecture";
}

export function dialogProgramLabelText(cat) {
  const mod = dialogProgramLabelMod(cat);
  return DIALOG_PROGRAM_LABELS[mod] ?? DIALOG_PROGRAM_LABELS.lecture;
}

export const SCREENING_SLIDESHOW_INTERVAL_MS = 12000;
export const HERO_SPOTLIGHT_SLIDE_INTERVAL_MS = 5000;

export const TEST_PAGE_NOTICE = Object.freeze({
  "ENABLED": true,
  "VALID_UNTIL": "2026-05-31",
  "STORAGE_KEY": "mxm2026_testPageNoticeDismissed_v1"
});

export const EXHIBITION_UI = Object.freeze({
  "mode": "auto",
  "fullDetailFrom": "2026-07-18"
});

export const FEATURED_EVENT_IDS = Object.freeze([
  "evt-01",
  "evt-04"
]);
export const FEATURED_PICKUP_CAROUSEL_INTERVAL_MS = 12000;

export const FEATURED_IMAGE_BY_ID = Object.freeze({
  "evt-01": "./images/evt-01.png",
  "evt-04": "./images/evt-04.png"
});

export const FEATURED_IMAGE_FALLBACK = "./images/image_12.jpeg";
