#!/usr/bin/env node
/**
 * js/config.js を生成（ブラウザ用・config.shared.js への import なし）。
 * Usage: node scripts/generate-config.mjs sheet|local
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const mode = (process.argv[2] || "sheet").trim();

if (mode !== "sheet" && mode !== "local") {
  console.error("Usage: node scripts/generate-config.mjs <sheet|local>");
  process.exit(1);
}

const shared = await import(pathToFileURL(join(root, "js", "config.shared.js")).href);

const {
  createSiteConfig,
  DATA_URLS,
  SHEET_DATA_URLS,
  LOCAL_DATA_URLS,
  PROGRAM_TIMELINE,
  DIALOG_PROGRAM_LABELS,
  EVENT_CATEGORY_LABELS,
  SCREENING_SLIDESHOW_INTERVAL_MS,
  HERO_SPOTLIGHT_SLIDE_INTERVAL_MS,
  TEST_PAGE_NOTICE,
  FEATURED_EVENT_IDS,
  FEATURED_IMAGE_BY_ID,
  FEATURED_IMAGE_FALLBACK,
} = shared;

const SITE_CONFIG = createSiteConfig(DATA_URLS[mode]);

function freezeLiteral(value) {
  return `Object.freeze(${JSON.stringify(value, null, 2)})`;
}

const out = `/** AUTO-GENERATED by scripts/generate-config.mjs (${mode}) — edit js/config.shared.js */
/** ブラウザはこのファイルのみ読み込みます（config.shared.js は Node 用ソース）。 */

export const DATA_MODE = ${JSON.stringify(mode)};

export const SITE_CONFIG = ${freezeLiteral(SITE_CONFIG)};

export const SHEET_DATA_URLS = ${freezeLiteral(SHEET_DATA_URLS)};
export const LOCAL_DATA_URLS = ${freezeLiteral(LOCAL_DATA_URLS)};
export const DATA_URLS = ${freezeLiteral({
  sheet: SHEET_DATA_URLS,
  local: LOCAL_DATA_URLS,
})};

export const PROGRAM_TIMELINE = ${freezeLiteral(PROGRAM_TIMELINE)};

export const EVENT_CATEGORY_LABELS = ${freezeLiteral(EVENT_CATEGORY_LABELS)};

export const DIALOG_PROGRAM_LABELS = ${freezeLiteral(DIALOG_PROGRAM_LABELS)};

export function dialogProgramLabelMod(cat) {
  if (cat === "workshop") return "workshop";
  if (cat === "permanent") return "permanent";
  if (cat === "screening") return "screening";
  return "lecture";
}

export function dialogProgramLabelText(cat) {
  const mod = dialogProgramLabelMod(cat);
  return DIALOG_PROGRAM_LABELS[mod] ?? DIALOG_PROGRAM_LABELS.lecture;
}

export const SCREENING_SLIDESHOW_INTERVAL_MS = ${SCREENING_SLIDESHOW_INTERVAL_MS};
export const HERO_SPOTLIGHT_SLIDE_INTERVAL_MS = ${HERO_SPOTLIGHT_SLIDE_INTERVAL_MS};

export const TEST_PAGE_NOTICE = ${freezeLiteral(TEST_PAGE_NOTICE)};

export const FEATURED_EVENT_IDS = ${freezeLiteral(FEATURED_EVENT_IDS)};
export const FEATURED_PICKUP_CAROUSEL_INTERVAL_MS = ${SCREENING_SLIDESHOW_INTERVAL_MS};

export const FEATURED_IMAGE_BY_ID = ${freezeLiteral(FEATURED_IMAGE_BY_ID)};

export const FEATURED_IMAGE_FALLBACK = ${JSON.stringify(FEATURED_IMAGE_FALLBACK)};
`;

const outPath = join(root, "js", "config.js");
writeFileSync(outPath, out, "utf8");
console.log(`Wrote js/config.js (DATA_MODE=${mode}, standalone)`);
